---
# Основной плейбук для установки и настройки Docker
- name: Docker installation and configuration
  become: true  # Повышение привилегий для выполнения задач
  block:
    - name: Set docker_required_packages based on host group
      set_fact:
        docker_required_packages: "{{ common_packages + docker_required_packages[ansible_group] }}"
      vars:
        ansible_group: "{{ 'web' if 'web' in group_names else 'db' }}"  # Определение группы хоста

    - name: Install Docker and required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ docker_required_packages }}"
        - docker-ce
        - containerd.io
      # Использование списка для установки пакетов одной задачей

    - name: Ensure Docker GPG key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        validate_certs: yes
      register: docker_gpg_key
      ignore_errors: true
      # Установка GPG ключа с проверкой и регистрацией результата

    - name: Re-add Docker GPG key if necessary
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_gpg_key.changed
      # Переустановка GPG ключа, если это необходимо

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] | lower }} stable"
        state: present
      # Добавление репозитория Docker

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started
      # Включение и запуск сервиса Docker

    - name: Add users to the docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      loop: "{{ docker_users }}"
      # Добавление пользователей в группу docker

    - name: Install Docker Compose via package manager
      apt:
        name: docker-compose
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal'
      # Установка Docker Compose через пакетный менеджер

    - name: Ensure docker-compose command is available for users
      shell: "docker-compose --version"
      become: false
      # Проверка доступности команды docker-compose для пользователей

  rescue:
    - name: Handle errors in Docker installation block
      debug:
        msg: "An error occurred during Docker installation."
      # Обработка ошибок в блоке установки Docker

  always:
    - name: Final check and clean-up
      debug:
        msg: "Docker installation and configuration completed successfully."
      # Финальная проверка и очистка после выполнения плейбука
